### ISSUE TITLE
Bad Actor Management

### ISSUE THREAD

**Issue by bombodo** [RomainLK/ytc-filter#3]
As the popularity of this tool will continue to increase alongside vtubers/YTlive, more people will begin to abuse and spam commonly used chat filters.

Can you add onclick functionality to each "vc-message-item" so that users can add chatters to whitelists/blacklists on the fly? Would also be great to enable sharing functionality so that well respected community translators can be easily added to user whitelists.

**Comment by RomainLK** [comment]
I can see your concerns about spam. I will consider something for that, but I hope it won't have to come to that. Let's try reporting them with Youtube's  built-in system first.

If it's not enough, then perhaps I will add a whitelist function. Whitelisting is easier for people as they just need to pick a finite number of people instead of unlimited number of spammer. It's also easier to vet a whitelist if sharing.

For sharing, I would rather not have to maintain a server for this. For now I can see a solution using Github + Netlify. Adding people to the whitelist would go through an issue or merge request, with a vetting process like providing a timestamped stream where we can see the translation.  Then everything is deployed to CDN thanks to Netlify. Netlify also has some serverless form feature which I could try.

Everything considered, this is a rather large feature to implement. Priority for this feature will depend on the evolution of the communities.

**Comment by bombodo** [comment]
Oh yeah, in hindsight, I can definitely see how a blacklist can grow out of control in size. 
With regard to using the Youtube reporting system, the spam could be negligible compared to the chat speed, but overwhelming when compared to translator/filtered speed. It would require the user stopping chat and manually scrolling through tens of messages to find and report the offender. 

What would be involved in writing a script to stop scrolling and jump to the specific timestamp of the offending spam message? (presumably using onclick)

**Comment by RomainLK** [comment]
> What would be involved in writing a script to stop scrolling and jump to the specific timestamp of the offending spam message? (presumably using onclick)

It should be possible, and the user better be fast otherwise the message will get erased from Youtube chat. It does feel like a needed feature.
