### ISSUE TITLE
Chat freezes after some time

### ISSUE THREAD

**Issue by Seraphaestus** [RomainLK/ytc-filter#40]
While using the firefox addon, chat eventually freezes after some time watching the video, stopping parsing new messages even as the stream continues. The session stats also reflect this pause, with number not going up. This is while watching a stream VOD. It can be fixed with a reload but that's not an ideal solution for actual streams.

**Comment by RomainLK** [comment]
Hello

Just to be sure, do you mean that Youtube's chat is freezing, or does it keep scrolling but ytc's stats are not going up? 

Also, do you have the URL for the video where you get the issue so that I can test please?

**Comment by Seraphaestus** [comment]
Both youtube's chat and the ytc filter chat froze, yeah; it didn't keep scrolling
I believe the vod was https://www.youtube.com/watch?v=RfnJ3zFgUuU
That was the first time I used the add-on and it hasn't happened again while watching another stream vod

**Comment by RomainLK** [comment]
I have tried this VOD with the extension disabled and the chat did freeze on my end. There is a number of report online about Youtube chat freezing and I don't think they are using the extension. It could be a bug from Youtube which is known for its already poor performance.

If it's a perfomance issue for Youtube, then ytcFilter is exacerbating it since it's tackled over it and does require some more power. For now, I don't think there is anything I can do as vanilla Youtube already have the issue. I have some ideas to increase the performance of ytcFilter so that it's less intensive but they are not my primary focus.
