### ISSUE TITLE
Filters Migrated From Old Version to 2.0.0 are blanked

### ISSUE THREAD

**Issue by blaxter75** [RomainLK/ytc-filter#49]
Browser: Chrome 87.0.4280.88
OS: Win 10 Home

The extension has never had the default profiles mentioned in the description for me so I have no idea how to get those. I manually set up my own filters and saved a global profile. It auto updated at some point yesterday to 2.0.0 and when it did that it had some issue with migrating the profile. Loading a Youtube video will say that the global profile gets applied but on initial load, going to settings, there are no profiles in the pulldown to select. Refreshing the page will show the migrated profile again.

Additionally, the profile's filters are all blanked. If I click show filters, no matter what I do (first load, refresh, apply/reapply profile), all I see is a list of the rubbish bin to delete filters but the filters do not show what they are/were.

**Comment by Googolplexbyte** [comment]
Having the same issue with v2. The profile I was using isn't applying any filter. I remade the profile, but it's not auto-applying anymore and when I manually click apply it doubles up and list every filter twice.

I think it's not auto applying because the "Auto open:" checkbox unchecks whenever I open a new stream.

**Comment by RomainLK** [comment]
Default profiles are available in the new popout the first time. There will be a info box with a green button which will allow you to load these profiles. If you missed the button, you can still load default profiles through the "Help" tab of the popout.

Also I know there is a number of issue with v2.0.0. due to migrating from 1.8.0, and also fresh install. I have already pushed to review on the Chrome webstore a 2.0.2. Sadly it's a slow process, which is quite painful to me as there are lots of reports

In the mean time, if you need to fix ytcFilter, you should backup your filters on a video through the export feature ( even if you have empty filters ). Bonus if someone can test for me: reimport those immediately. Otherwise then in the Popout > Help tab, click on "Full reset"

**Comment by blaxter75** [comment]
I tried the export/reimport when I was trying to figure out what went wrong with the empty filters. All it did was double the amount of empty filters (I'm assuming it was just replicating the same empty filters).

**Comment by RomainLK** [comment]
Oh, do you still have the content which was in clipboard? If you don't it's ok. I seriously hope 2.0.2 will solve most problems.

Sorry for the inconvenience orz.

**Comment by blaxter75** [comment]
Apologies, I do not. I uninstalled the old version and 2.0.0 and manually installed 2.0.2 off Git

**Comment by Googolplexbyte** [comment]
Yep, 2.0.2 seems to have solved all my issues.

**Comment by RomainLK** [comment]
2.0.2 is officially out on Chrome's web store.
