### ISSUE TITLE
ytc filter not picking up messages

### ISSUE THREAD

**Issue by HeyHeyHayden** [RomainLK/ytc-filter#76]
Running the ytc filter version: 2.1.3. I've noticed that since the extension was updated with the popout it seems to no longer be able to detect messages. I've been using the messages from staff preset and no matter how many moderator or owner messages are sent in chat ytc does not pick up any of them.

I've tried using other presets and custom presets and it cannot detect any messages. Uninstalling and reinstalling does not fix it either.

It might have something to do with it being the archives of streams that I'm watching but I'm not too sure. 

Would appreciate any help you can give me.

Edit: I tried testing it out and it does work on live streams, but not archived ones. Might just be an issue with owner/moderator messages on archives on youtubes side, not the extension.

**Comment by RomainLK** [comment]
Strange, I usually test with VOD because I don't have always have a livestream. If you have a link to a specific video, I could test with it. 

I would also like a copy of your configuration. In order to have one in 2.1.3, you need to open the Popout, then with focus in it, the Debugger with F12. There is a console tab in which you paste 

`chrome.storage.local.get(s => console.log(JSON.stringify(s)))`

**Comment by HeyHeyHayden** [comment]
I'm assuming this is what you were after?

{"@@vwe-persistence":{"global":{"compactPopout":{"height":800,"width":1200},"darkMode":true,"defaultPerChannel":{},"fullPopout":{"height":1407,"width":1294},"globalDefault":"7lefkqjry","limitMsgPerVideo":100,"profiles":{"7lefkqjry":{"filters":[{"caseSensitive":false,"type":"isModerator","value":null},{"caseSensitive":false,"type":"isOwner","value":null}],"key":"7lefkqjry","name":"Streams","options":{"autoOpen":true,"autoScroll":true}},"alphanumeric":{"filters":[{"type":"regex","value":"/[a-z0-9]/i"}],"key":"alphanumeric","name":"Messages with alphanumeric","options":{"autoMaxHeight":false,"autoOpen":false,"autoScroll":true,"height":100}},"englishtag":{"filters":[{"type":"regex","value":"/^[[(]?(?:eng?|t(?:(rans|l))+|英訳)(?:/(?:eng?|t(?:(rans|l))?|英訳))?[\\]): -]/i"}],"key":"englishtag","name":"English tagged messages","options":{"autoMaxHeight":false,"autoOpen":false,"autoScroll":true,"height":100}},"japanese":{"filters":[{"type":"regex","value":"/[一-龠]|[ぁ-ゔ]|[ァ-ヴー]|[ａ-ｚＡ-Ｚ０-９]|[々〆〤]/u"}],"key":"japanese","name":"日本語/Messages with japanese characters","options":{"autoMaxHeight":false,"autoOpen":false,"autoScroll":true,"height":100}},"staff":{"filters":[{"type":"isModerator"},{"type":"isOwner"}],"key":"staff","name":"Messages from staff","options":{"autoMaxHeight":false,"autoOpen":false,"autoScroll":true,"height":100}}},"storageLifetime":7,"version":"2.1.3"},"helpAlert":{"filterHelp":false,"profileDefaultHelp":true,"profileHelp":false,"welcome":false},"videoSettings":{"L1a0zYpKRHQ":{"channelId":"UCHsx4Hqa-1ORjQTh9TYDhww","channelName":"Takanashi Kiara Ch. hololive-EN","feeds":{"default":{"deduplication":{},"filters":[{"type":"isModerator"},{"type":"isOwner"}],"messages":[]}},"id":"L1a0zYpKRHQ","lastViewed":"2021-01-30T13:20:59.314Z","name":"【#HOLOTALK​】With our 5th guest: Sakura Miko #EliTori​ #エリー鳥​","options":{"autoMaxHeight":false,"autoOpen":false,"autoScroll":true,"height":100}}}}}

**Comment by RomainLK** [comment]
Yes thank you. Indeed you have a very empty archive. On any of these stream, is the statistic counter in the bottom right at least increasing? Also, do you have any other extension which modify Youtube? I take you are on Chrome since you are still on 2.1.3.

**Comment by HeyHeyHayden** [comment]
The statistic counter in the bottom right does increase as the video goes on, so I assume it is reading the messages. The only other extension I have installed is an ad-blocker, so it shouldn't be causing any problems. 

This is the error code that pops up in the console: 
DevTools failed to load SourceMap: Could not load content for chrome-extension://mnldnbhgfocmkehnlkeanlhfmopepnko/popper.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by koriar** [comment]
I've had the same issue. I created a test profile to show every message with 'e' in it just to make sure, and I got nothing. (Also having to open the popout every time I want to switch profiles really sucks)

The counter DOES go up, but I see messages like these in the console. Testing on Gura's stream happening live right now, but these messages are from around 40 minutes in.

https://www.youtube.com/watch?v=eJ5OuEhbNcE

[ytcFilter] Unsupported chat action {clickTrackingParams: "CAEQl98BIhMI9PbTvZLF7gIVKZ6cCh3FLgsd", addChatItemAction: {…}}
VM26111 inject.js:4646 
[ytcFilter] Unsupported chat action {clickTrackingParams: "CAEQl98BIhMI9PbTvZLF7gIVKZ6cCh3FLgsd", addLiveChatTickerItemAction: {…}}

I closed the chat and reopened it and the full console logs from that point (with the filter set to 'message contains e' are:

[ytcFilter] DOM loaded.
content.js:46191 [ytcFilter] Primary element: true  Message Mount from DOM loaded
content.js:45445 [ytcFilter] Mounted hook start
content.js:46197 [ytcFilter] Mounting
content.js:45460 [ytcFilter] Bootstraping
content.js:45700 [ytcFilter] Last version detected: 2.1.3
content.js:45593 [ytcFilter] Mounted hook end
content.js:40154 [ytcFilter] Message List mounting. Video id: eJ5OuEhbNcE
DevTools failed to load SourceMap: Could not load content for chrome-extension://mnldnbhgfocmkehnlkeanlhfmopepnko/FileSaver.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
content.js:45568 [ytcFilter] Switching to fetch interceptor
[ytcFilter] Unsupported chat action {clickTrackingParams: "CAEQl98BIhMI7d7y9JPF7gIVmAXWAB1RWQeZ", addLiveChatTickerItemAction: {…}}
inject.js:4646 [ytcFilter] Unsupported chat action {clickTrackingParams: "CAEQl98BIhMI2dPB-pPF7gIV8cXBCh099Aqh", addLiveChatTickerItemAction: {…}}
inject.js:4646 [ytcFilter] Unsupported chat action {clickTrackingParams: "CAEQl98BIhMIjKO3_ZPF7gIVGfDBCh3XyQc6", addLiveChatTickerItemAction: {…}}
inject.js:4646 [ytcFilter] Unsupported chat action {clickTrackingParams: "CAEQl98BIhMIjKO3_ZPF7gIVGfDBCh3XyQc6", addChatItemAction: {…}}
inject.js:4646 [ytcFilter] Unsupported chat action {clickTrackingParams: "CAEQl98BIhMIjKO3_ZPF7gIVGfDBCh3XyQc6", addLiveChatTickerItemAction: {…}}


I disabled all extensions that interact with Youtube, including ad blocking, though the previous version worked with all my extensions.

It also seems to be increasing CPU usage a LOT whenever chat is open for more than a few minutes. Like to where the video stops playing until I close chat.

**Comment by koriar** [comment]
Huh... interestingly if I go to Kiara's debut stream I DO see my default filters working... I don't think it's a live/archive thing as I watched the Holotalk archive and people were saying that Amelia said something in chat but nothing was filtered. I'll do some more testing.

**Comment by RomainLK** [comment]
@HeyHeyHayden 
For your error about SourceMap, it's not important, that's just a file which the debugger can use, but it has no effect on the inner working of ytcFilter

Youtube's chat is also a natural CPU burner... I have seen people optimize it and it's possible I will have to do it too :(

@koriar 
I have some plan to add some quick config option, using that useless ytcFilter button in the toolbar.

The unsupported chat action is normal, it's for message like paid stickers, which today ytcFilter doesn't have any filter for. I have removed those logs in the latest version.

On Coco stream I have used your regex ".*" and got all of them ( 1002/1002 currently ). However I actually suspect that's because I'm on VOD, and if you were on Livestream, there is some difference. Youtube can add some garbage in its server message during livestream compared to VOD, especially for fast chat.

Can you try updating to the latest version 2.1.6? There is a fix for invisible characters, and also message without author which invalidate a whole batch.

https://github.com/RomainLK/ytc-filter/releases

I will wait for another live with fast chat to test some more.

Also, just for my curiosity, can you paste this in the console:

`window.ytcfg.data_.INNERTUBE_CLIENT_VERSION`

This will give me the version of Youtube normally (I just discovered this like right now)

**Comment by koriar** [comment]
@RomainLK 
I've never installed an extension outside of the official channels so I might be doing this wrong. I grabbed the zip file, extracted it to a folder, and used "Load unpacked" from the Manage Extensions page to load it in.

It appeared in the list, but I got an error.

![image](https://user-images.githubusercontent.com/9036862/106397607-5c741b00-63dc-11eb-95f5-1bc2c3adb052.png)

Here's the output of that in the console from Ina's stream happening right now.
window.ytcfg.data_.INNERTUBE_CLIENT_VERSION
"2.20210128.02.00"

**Comment by koriar** [comment]
Ah, looks like that error didn't actually prevent me from using the extension. I can confirm that I'm getting 100% of the messages with the .* regex now, though Ina stream has a lot slower chat than Coco or Gura's big streams.

I tried the console command with both the new and old versions and they both had the same output.

**Comment by RomainLK** [comment]
Ok thanks. Good to know that the new version improves the situation. It's still in review by Google at the moment so it will take some time until it's released.

As for the unrecognized manifest error, that's normal; it's a configuration specific to Firefox, and Chrome doesn't understand it.

Otherwise same version as me for the innertube, whatever it's.

**Comment by RomainLK** [comment]
2.1.6 was released after 5 days in Google review hell!
