### ISSUE TITLE
Block option from filter

### ISSUE THREAD

**Issue by rakankrad** [RomainLK/ytc-filter#87]
I wonder if it would be possible to add an option to block a user from showing up in the filter when they misuse one of the tags. 

Some people use [en] in the holoEN streams when unnecessary, adding an option to blacklist their names from showing up in the filter with a single click feels like it would be a nice addition.

**Comment by RomainLK** [comment]
If you click on the message, you will get access to the message actions. Among them, there might be 3 dots, on the left. It's the Youtube block button which you can use to report spam/block user. There is a few caveat though: the button only appears when the message is in Youtube's chat, which means, it will not appear immediately as ytcFilter can load them before they appear, and it will disappear after a while.

This is designed like that in order to fight spam globally, not just for the user of the extension. I have considered several time the use of a block list in ytcFilter, and for now I would like to leave it like that, but I'm still open to make it happen if I see a serious need which can't be covered by the current integration of Youtube's block button ( or if Youtube is a buggy mess with the block button )

**Comment by rakankrad** [comment]
Thanks, I had not noticed the three dots that are on the ytc window and was quite annoyed since youtube itself doesn't let me block the person from the main chat. The three dots do not show up in the normal chat for them.
